### ISSUE TITLE
Button onPress does not respond to clicks; Cannot inspect elements;

### ISSUE THREAD

**Issue by tylerssn** [criszz77/luna#51]
**Describe the bug**
`<Button title={"title"} onPress={()=>alert('test click')} />` does not respond to clicks.

Inspecting the element in Chrome tools sends me to an iframe that masks the application.

**To Reproduce**
1. Replace the content of `app.tsx` with
   ```jsx
   export default () => <Button title={"test"} onPress={()=>alert("test")} />
   ```
3. Run `yarn web`
4. Click on the button

**Expected behavior**
Alert "test"

**Desktop (please complete the following information):**
 - Browser: Brave browser
 - Version: 1.36

**Comment by tylerssn** [comment]
This is actually caused by an iframe that is being injected to the bottom of the page some how but has a fixed position with 100% with and height. 

Working around this until I figure out the cause with `iframe {display: none}`

**Comment by criszz77** [comment]
I'm sorry but I could not reproduce it. Please try Google Chrome. I tried multiple browsers, and I always returned to Google Chrome. For development and personal use as well.

**Comment by mikehardy** [comment]
I use Brave, it works. This will need an App.js we can drop in
https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
