### ISSUE TITLE
Not work with GestureHandlerRootView on web

### ISSUE THREAD

**Issue by 1280103995** [criszz77/luna#53]
**Thanks your template** 👏 👏 👏 
-----------

**Describe the bug**
1. i run `yarn add react-native-reanimated`.
2. according to the `react-native-gesture-handler` installation documentation to use `GestureHandlerRootView`, then the page is blank on the web.

**src/index.js**
```
import 'react-native-gesture-handler';
...
```

**App.tsx**
```
import {GestureHandlerRootView} from 'react-native-gesture-handler';
...

const TabbedApp = () => {
  return (
    <SafeAreaProvider initialMetrics={initialWindowMetrics}>
      <GestureHandlerRootView style={{flex: 1}}>    // add
        <NavigationContainer>
          <TopTabNavigator />
        </NavigationContainer>
      </GestureHandlerRootView>                     // add
    </SafeAreaProvider>
  );
};
```

**To Reproduce**
Use default template

**Expected behavior**
These popular libraries should work fine on the web, no?

**Comment by criszz77** [comment]
Hello @1280103995 . Thank you for trying my template and for raising this issue. 

Indeed, these popular libraries should work well in the web. There might also be the case that for the web there would be needed some certain styles to display your view. 

Unfortunately, I don't think I will have time until the weekend to have a look at it. If you resolve the issue in the meantime, I would appreciate if you come back here with an answer.

Thank you! 🙏

**Comment by criszz77** [comment]
@1280103995 Removing from **src/index.ts** the following works for me: 

```javascript
import 'react-native-gesture-handler';
...
```

Adding it to **./index.ts** (from root) should only import it for Android and IOS.

I'm not sure if that's the correct way to go. Maybe we should open an issue @react-native-gesture-handler

**Comment by criszz77** [comment]
First fix:
-  https://stackoverflow.com/a/70573596/14056591
Second fix: 
 - https://stackoverflow.com/a/62297869/14056591 
 - https://github.com/gsoft-inc/craco/issues/55#issuecomment-719714009

**Comment by 1280103995** [comment]
Thanks, the new version works fine.

**Comment by criszz77** [comment]
Please use **v1.2.8**.

In **v1.2.7,** I managed to introduce a small bug.
